### ISSUE TITLE
Instructions to get it working in UITableViewController

### ISSUE THREAD

**Issue by magnett** [telly/TLYShyNavBar#11]
Hi!
Thanks for this control, truly great work!
In my case, the screenshot you see below is from a UITableViewController. The position of the drawer is wrong and i can not scroll the whole table. I made an experiment and used a UIVIewController and everything worked smoothly.
Is anything special i can do to get it working with a UITableViewController?
![ios simulator screen shot jul 12 2014 20 00 46](https://cloud.githubusercontent.com/assets/1730803/3562242/9cac94ba-09e6-11e4-9053-6c8be32f7cdf.png)

**Comment by Mazyod** [comment]
Since the repo has a UITableViewController example now, I suppose this issue should be closed. If there are any more specific issues, please reopen or specify the exact issue

**Comment by rrallo** [comment]
So is the only workaround to migrate to a ViewController with a tableview inside of it? This issue only happens to me on iOS 7.1.

Amazing job on the repo though!

**Comment by yuchaozh** [comment]
I met the same issue right now. Where is the example for UITableViewController?
