### ISSUE TITLE
TabBarController in Navigation controller results to no nav bar collapsing

### ISSUE THREAD

**Issue by radimhalfar** [telly/TLYShyNavBar#112]
I have a UITabBarController in UINavigationController. The Bar controller is RootVc of Navigation Controller and I want in childViewController use shyNavBar. But if I try, even if I pass the scroll view to TabBarController it doesn't work at all. 

NavController -> TabBarController -> Tabs(Here to use framework). 
The ChildVC is ViewController with table and I am passing tableView to manager's scroll view property. 

Language Swift

[EDIT]
It works if I assign tab bars manager as childs and only as I come to screen on second time

[EDIT2]
Please add to your guide, that the manager has to be assigned after the tableView is filled with data!

**Comment by Mazyod** [comment]
Thanks for the feedback. The library explicitly observes `contentSize` of the `scrollView`, so it doesn't need to be assigned after the data is filled. It should work as long as you assign the `scrollView` after you've hooked up your delegates, as mentioned in the docs.

Maybe I need to investigate more on this, but I'm sure it's not related to the tableView data not being filled.
