### ISSUE TITLE
Collection view frame moved to left on first scrolldown

### ISSUE THREAD

**Issue by bbreier** [telly/TLYShyNavBar#113]
In some cases, a collection view's frame can be offset to the left the first time the user scrolls and the navbar is hidden. Afterwards, it tends to snap back towards the original frame but one or two pixels off. This behavior is non deterministic in that the amount of offset and whether it snaps back to the original frame is different with each test.

**Comment by MichaelDanielTom** [comment]
+ 1, I'm getting the same problem, except with a tableview and the frame's height shrinks nondeterministically. It's always on the first scroll and I have a hunch that it has to do with the scrollview being managed by another uiviewcontroller.

**Comment by Mazyod** [comment]
Thanks to #114 this should be closed... I will make a new release as soon as pending PRs are either merged, closed, or deemed too much to handle for a quick release.
