### ISSUE TITLE
Black effect when set translucent property to "no" in navigation bar

### ISSUE THREAD

**Issue by Venko132** [telly/TLYShyNavBar#127]
Hi, i've got hierarchy of controllers like this https://github.com/telly/TLYShyNavBar/issues/112,
but when I set  translucent property to "no" for navigation bar, I get black effect when scroll table
(https://cloud.githubusercontent.com/assets/5242687/13523498/80a6976a-e1fe-11e5-97b7-129ee655bcd1.png)

**Comment by tiois** [comment]
I was going crazy until I saw this issue, got the same problem here! I got a black opaque navigation bar, and when the bar disappears when scrolling down, I also get a black bar where the navigation bar was.

**Comment by tiois** [comment]
For those wondering how to fix this, you have to check the «Extend Edges» `Under Opaque Bars` in the View Controller configuration.

**Comment by Mazyod** [comment]
Thanks for reporting this. I'll add your solution to the FAQ, @tiois. Cheers.
