### ISSUE TITLE
Extension view flickering issue

### ISSUE THREAD

**Issue by maxgorodivskyi** [telly/TLYShyNavBar#141]
Hello, I've encountered issues with extension view when there are certain amount of cells in table view (approximately view.frame.height/cell.frame height + 1).
It is easy to reproduce in demo setting number of rows to 16

How it looks:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/18209424/14679639/7223fc1a-0723-11e6-8bb2-019a28c206a7.gif)

**Comment by ndrewh** [comment]
I noticed this as well. I have a fix on my fork and might submit a PR soon, but my fix probably causes more problems that I haven't noticed yet.

**Comment by vineeth90** [comment]
Hi,
I am also facing the same flickering issue. Its working fine with the fix provided. I did some rounds of testing and its looking good for me.  Can anyone confirm whether this fix is making any other issues ?
