### ISSUE TITLE
It will be swift Edition？

### ISSUE THREAD

**Issue by huangboju** [telly/TLYShyNavBar#156]

**Comment by tiois** [comment]
It's already working with Swift, simply make a bridging header file : https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by huangboju** [comment]
I know it can working with Swift,
but I want to translate it into swift，
in some places I do not know how to do
this is my repostory  https://github.com/huangboju/TLYShyNavBar.swift

**Comment by Mazyod** [comment]
@huangboju Yes, this repo heavily relies on the ObjC runtime functionality, in which some of it is not directly exposed to Swift. This makes the library ideal to be developed in ObjC rather than Swift.
