### ISSUE TITLE
Black navigation bar

### ISSUE THREAD

**Issue by Pitometsu** [telly/TLYShyNavBar#161]
If harshly swipe over screen down, navigation bar not appears so it looks like on screenshots:

![screenshot1](http://i.imgur.com/y3wWTRr.png?1)

---

![screenshot2](http://i.imgur.com/nrhTaGY.png?1)

**Comment by Pitometsu** [comment]
Yes, I have all the under-*** checked in all view controllers according to https://github.com/telly/TLYShyNavBar#opaque-navbar-shows-black-bar-when-scrolled-up .

Note, I have following configuration: NavigationController > ViewController(Shy) > Container > TableViewController. BTW is it feature: if I have some vertical offset for Container with TableViewCntroller, shy controller just ignoring it.

**Comment by RJiryes** [comment]
Any updates?

**Comment by Pitometsu** [comment]
@RJiryes yes, I put custom header into custom bar inherited from `UINavigationBar` and use `pod 'JDFPeekaboo'` instead. It solved most problems.
