### ISSUE TITLE
Double Status Bar Support

### ISSUE THREAD

**Issue by insanj** [telly/TLYShyNavBar#18]
When in-call or tethering, the margins aren't quite correct for both ```shyNavBar``` states. For my ```UITableView```-embedded ```UIViewControllers``` the hidden state remains 20px, and isn't pushed behind the 40px status bar. In addition, after revealing the ```shyNavBar```, the navigation bar grows to 62px (the 20px appendage on the double status bar remains below it). When the content in my scroll view is not pushaway-scrollable (smaller than the frame), the small contraction when bouncing it offsets the navigation bar behind the status bar, as well.

I'm not certain if every one of these issues is completely attributable to ```TLYShyNavBar```, but I'm certain at least the first and mutations of the rest are likely to exist in other apps. If these results are intentional, please let me know if there's something else I should do with the view controller to make the presentation less intrusive.

**Comment by stasix** [comment]
Hi @koenbud, was wondering if you worked it out. I'm struggling with this now.

**Comment by Remki** [comment]
Hi,

I created pull request with fix for this bug:
https://github.com/telly/TLYShyNavBar/pull/62

**Comment by Mazyod** [comment]
Merged. I hope this one is finally fixed. Cocoapods version bumped, as well.
Thanks again @Remki
