### ISSUE TITLE
Support for iOS 12 and Xcode 10 beta

### ISSUE THREAD

**Issue by akshya672222** [telly/TLYShyNavBar#197]
We are with a little problem on TLYShyNavBar in iOS 12 using Xcode 10 beta. The TLYShyNavBar was working fine in my app until the last version, but when I updated to iOS 12 and Xcode 10, the app doesn't compile anymore.

This is what I am getting from Xcode:
Multiple commands produce '/Users/…/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphoneos/TLYShyNavBar/TLYShyNavBar.framework/Info.plist':
1) Target 'TLYShyNavBar' has copy command from '/Users/…/Desktop/…/Pods/TLYShyNavBar/TLYShyNavBar/Info.plist' to '/Users/…/Library/Developer/Xcode/DerivedData/…/Build/Products/Debug-iphoneos/TLYShyNavBar/TLYShyNavBar.framework/Info.plist'
2) Target 'TLYShyNavBar' has process command with input '/Users/…/Desktop/…/Pods/Target Support Files/TLYShyNavBar/Info.plist'

Could you help me?

**Comment by DmitryArbuzov** [comment]
You can fork this repository and modify .podspec file.
Just add Info.plist to `exclude_files`.
Example:
`s.exclude_files = "TLYShyNavBar/Info.plist"`
