### ISSUE TITLE
PushViewController with NavigationBarHidden = YES

### ISSUE THREAD

**Issue by basilmariano** [telly/TLYShyNavBar#21]
Hi, 
I have been using this library since you published, and I really like it so much!
and I am using this on my current project right now, :)

I have just small issues:

I have project that pushes to navigation on appear setNavigationBarHidden = YES

The effect is:
- the navigationBar will be hidden on the transition effect and the extensionView will be left shown (seems not good to see)

question: 
1. Can we also set the extensionView hidden when Navigation is hidden?
2. when pushed and the extensionView and the navigation is hidden, can we let it be hidden upon push to another viewController? because right now when I push, It automatically shows the navigation and extensionView

Sorry for noob question :)

**Comment by joshbernfeld** [comment]
If you are pushing to a view controller that does not have a shyNavBar from a view controller that does have a shyNavBar and you are hiding the nav bar in viewWillAppear of the new controller it will not work. Here is the solution that works great for me.
```

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    //We have to manually animate hiding the nav bar because TLYShyNavBar prevents
    //[self.navigationController setNavigationBarHidden:YES animated:YES]; from animating properly.
    //First animate the bar out in viewWillAppear:, then call setNavigationBarHidden: in viewDidAppear:
    //This will allow user interaction underneath where the bar would normally be.
    
    [UIView beginAnimations:nil context:NULL];
    [UIView setAnimationDuration:0.25];
    self.navigationController.navigationBar.alpha = 0;
    [UIView commitAnimations];
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    
    [self.navigationController setNavigationBarHidden:YES animated:NO];
}


- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    
    //Prevents showing the navigation bar when moving to another of the same controller
    if (![self.navigationController.topViewController isKindOfClass:[YourViewController class]]) {
        [self.navigationController setNavigationBarHidden:NO animated:YES];
        
        [UIView beginAnimations:nil context:NULL];
        [UIView setAnimationDuration:0.25];
        self.navigationController.navigationBar.alpha = 1;
        [UIView commitAnimations];
    }
    
}

```
