### ISSUE TITLE
UITableView Header Section not scrolling properly

### ISSUE THREAD

**Issue by say8425** [telly/TLYShyNavBar#30]
Hello. I use your code wonderfully.
And this time I make a app with Instagram SDK.

So make a tableView and custom Header Section.
tableView issued is solved, but problem is Header Section.
When navigationBar hidden, Header Section is not follow just remained.

like this.
![2014-09-05 4 53 31](https://cloud.githubusercontent.com/assets/3258867/4161776/2e9b68e0-34d2-11e4-87bb-f2f2b07f144f.png)

How can I make Header section could move in navigationBar.position when it disappear?

**Comment by fimm** [comment]
- (void)scrollViewDidScroll:(UIScrollView *)sender {
    
    UIEdgeInsets inset = self.tableView.contentInset;
    inset.top = MAX(MIN(self.view.frame.size.height + 20, self.navigationController.navigationBar.frame.origin.y +self.navigationController.navigationBar.frame.size.height ), 20);
    [_tableView setContentInset: inset];
    
}

**Comment by mlabraca** [comment]
@fimm solution's worked well for me.
Thanks.

**Comment by awoczek** [comment]
If you've added optional ExtensionView to ShyNavBar it works for me:

    UIEdgeInsets inset = tableView.contentInset;
    
    CGFloat navBarY = self.navigationController.navigationBar.frame.origin.y;
    CGFloat navBarHeight = self.navigationController.navigationBar.frame.size.height;
    CGFloat navBarExtensionY = self.shyNavBarManager.extensionView.superview.frame.origin.y == 0 ? 64 : self.shyNavBarManager.extensionView.superview.frame.origin.y;
    CGFloat navBarExtensionHeight = self.shyNavBarManager.extensionView.superview.frame.size.height;
    
    inset.top =  MAX(MIN(self.view.frame.size.height + 20, navBarY + navBarHeight + (navBarExtensionHeight - ((20 + navBarHeight) - navBarExtensionY))), 20);
    NSLog(@"%f", inset.top);
    tableView.contentInset = inset;

**Comment by 0xc00010ff** [comment]
Thank you @fimm and @awoczek.
Went with @fimm's solution, one of us should make a pullrequest for functionality that inspects the scrollview to see if its `UITableView` kind of class, and if so, swizzle in the `scrollviewDidScroll` inset trick if `viewForHeaderInSection` returns a view.

**Comment by modastic** [comment]
For anyone who also has a UIRefreshControl setup, this code will take it into account:

```
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    if (scrollView.contentOffset.y > - (self.navigationController.navigationBar.frame.size.height
                                       + [UIApplication sharedApplication].statusBarFrame.size.height)) {
        UIEdgeInsets inset = self.tableView.contentInset;
        
        inset.top = MAX(MIN(self.view.frame.size.height + 20, self.navigationController.navigationBar.frame.origin.y + self.navigationController.navigationBar.frame.size.height), 20);
        [self.tableView setContentInset: inset];
    }
}
```

**Comment by evands** [comment]
Thanks, @awoczek -- this worked well for me.

**Comment by evands** [comment]
Update: @awoczek's solution works coincidentally but breaks in some edge cases.  Here is a clearer and more correct solution:
```objc
- (void)scrollViewDidScroll:(UIScrollView *)sender {
    UIEdgeInsets inset = sender.contentInset;
    CGFloat statusBarHeight = AACStatusBarHeight(self);
    
    if (self.shyNavBarManager.extensionView) {
        CGFloat maxExtensionBar = CGRectGetMaxY([sender.superview convertRect:self.shyNavBarManager.extensionView.superview.frame
                                                                     fromView:self.shyNavBarManager.extensionView.superview.superview]);
        inset.top = MAX(MIN(self.view.frame.size.height + statusBarHeight,
                            maxExtensionBar),
                        statusBarHeight);
    } else {
        CGFloat maxNavBar = CGRectGetMaxY([sender.superview convertRect:self.navigationController.navigationBar.frame
                                                               fromView:self.navigationController.navigationBar.superview]);
        
        inset.top = MAX(MIN(self.view.frame.size.height + statusBarHeight,
                            maxNavBar),
                        statusBarHeight);
    }
    
    sender.contentInset = inset;
    
    [super scrollViewDidScroll:sender];
}
```

**Comment by keyboardsamurai** [comment]
@evands works very well for me. Care to create a PR?

**Comment by evands** [comment]
I have this in my delegate.  If you'd like to integrate the fix into the code and make a pull request, please feel free!

**Comment by Mazyod** [comment]
been meaning to move to `convertRect:` methods for a while. This is a superb approach @evands!
