### ISSUE TITLE
Extension View Shown, recognizes proper View Controller, No hiding behavior

### ISSUE THREAD

**Issue by RoninSTi** [telly/TLYShyNavBar#35]
Hello,

***Update, I've narrowed down the cause of the issue, please scroll to stars to see***

I have a UIViewController embedded in a navigation controller.  Not sure if this is relevant, but a tabBarController is my root view controller.

Anyways I setup the shynavbarcontroller per the quick setup in viewDidLoad and set a tableView as the scrollview.  This code comes after functions thats setup the tableview and add it as a subview to the view controller.

I also created an extension view similar to the example project, which shows up fine.  There is no response to the tableview scrolling though.  Is there a setting or code I have in place that may cause the shynavbar to not "see" movements in the tableview?  The tableview behaves normally but the extension and the navbar never budge.

***UPDATE: If I remove - (void)viewWillAppear:(BOOL)animated function, the shynavbar behaves as expected.  Is this a bug?***

Setup code below, I'll post any other code that would help my situation:

    self.shyNavBarManager.scrollView = self.tableView;
    
    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.view.bounds), 44.f)];
    view.backgroundColor = [UIColor redColor];
    [self.shyNavBarManager setExtensionView:view];

**Comment by muppetkermit** [comment]
Thanks for opening this issue, interesting but removing viewWillAppear solves it. Do you know what causes that?

**Comment by Mazyod** [comment]
I don't think it will be easy to know what was going on then, so will close this for now.
