### ISSUE TITLE
Toggling the nav bar from being "shy" or not

### ISSUE THREAD

**Issue by lelandrichardson** [telly/TLYShyNavBar#43]
Hello,

Thank you so much for creating this component. The "shy" nav bar has become a very common UX practice and it's incredibly helpful to have  component like this that just works out of the box.

I have a table view which is using the shy nav bar. When there are "new items" available, a red alert label is shown in the nav bar to take them up to the top and see the new items.  This works great if the user actually sees the button, but if they are scrolling down they may not.  What I'd like to be able to do is force the nav bar to stay visible (ie, not contract on scroll) when new items are present, and be "shy" and work as normal otherwise.

I've looked through the source and I can't seem to find any methods to toggle this behavior. Am I just missing it?  If not, would this be something you'd consider adding?

Thanks!

- Leland

**Comment by Mazyod** [comment]
This should be resolved by @blackm00n's PR. Please reopen if not.

**Comment by paulius005** [comment]
Hey,

This is a great component, and is really quite easy to use. I have noticed that the disable flag was added, but it disables both the shy view and the navigation bar from hiding. I am trying to just hide the shy view while keeping the navigation bar static. Is this possible with the existing code, or is this functionality I should consider adding? Would this involve changing the node structure?

Thanks!

Paulius

**Comment by Mazyod** [comment]
@paulius005 Thanks. This component revolves around the NavBar, not the extension view. It might make more sense to implement a shy extension view using a custom collection view layout?

Regarding the change required to achieve what you want, yeah. I think if that method returns 0, it will just work.
