### ISSUE TITLE
bottomLayoutGuide is not adjusted in layoutViews

### ISSUE THREAD

**Issue by stasix** [telly/TLYShyNavBar#47]
I have opaque tab bar at bottom, and scrollView's content bottom inset is not adjusted in layoutViews. 
I use  [self setExtendedLayoutIncludesOpaqueBars:YES]. Any help?

**Comment by Mazyod** [comment]
Please check to see if #7 helps?

**Comment by stasix** [comment]
@Mazyod - that didn't help. It works great for navigation bar but not for the opaque tab bar.

**Comment by Mazyod** [comment]
I believe the bottomLayout is not the responsibility of this component. It only adjusts the `top` property for that reason.
