### ISSUE TITLE
How to use library with complicated structure viewcontroller

### ISSUE THREAD

**Issue by tatsuaka** [telly/TLYShyNavBar#48]
Thanks for your wonderful library.

I'm trying to hide NavigationController with this library but it's not working. I think that causes my ViewController is a little complicated.
My viewController extend AXStretchableHeaderTabViewController library whose structure is like below.

Stretchable HeaderView 
|
ParentContainerViewController 
|
|-- FirstSubViewController (CollectionView)
|-- SecondSubViewController (TableView)
|-- ThirdSubViewController(TableView)

ParentContainerView extends AXStretchableHeaderTabViewController and has UIScrollView as ContainerView. I try to set it like "self.shyNavBarManager.scrollView = self.containerView;" but not working also " [self.shyNavBarManager setExtensionView:stretchableheaderView Instance];" is not working.Even when I doing that in SubViewController, it was not working.

As if it is scrolling in SubViewController, I can not get scroll delegate in ParentContainer otherwise can not get navigationController and Navbar in SubViewController.

I saw your code but it's tough to find which part is not workig for me in my poor skill.
If you have any idea,  could you let me know what's wrong?

Thanks!

**Comment by Mazyod** [comment]
I am afraid I will need a demo project to test this. Can't think of why it won't work.
