### ISSUE TITLE
Programmatically changing content offset triggers TLYShyNavBar

### ISSUE THREAD

**Issue by koenbud** [telly/TLYShyNavBar#5]
I am developing a chat application where I set the content offset programmatically when inserting new rows in chat table view.

TLYShyNavBar trigger when this happens and shortly contracts the navigation bar. Is there a way to solve this?

For instance, temporarily disable ShyNavBar while programmatically changing the content offset or make it trigger only when the user is scrolling.

**Comment by Mazyod** [comment]
I think this was resolved by introducing the `disabled` property on the manager.
