### ISSUE TITLE
Issue while Implementing this code with UIScrollview

### ISSUE THREAD

**Issue by ajaypatil12** [telly/TLYShyNavBar#50]
Hi,

I have used your code in my application & it works pretty good. Only it shows issue while i am using the UIScrollView,

My Code structure is like below:
1. There is one view controller which contains a scrollView. Inside that scroll view i have loaded 4 another views. 
2. The scrolling of pages are only horizontally & all the view contains a collection view.
3. So when i scroll the collection view to up, the navigation bar is get hide as per requirement but while i scroll the UIScrollView horizontally the next view shows a white screen at a top (in place of navigation bar).

**Comment by Mazyod** [comment]
Thanks for using the library, but unfortunately I think this issue is out of scope.
