### ISSUE TITLE
shybar doesn't "unhide" when the tableview height or content height shrinks

### ISSUE THREAD

**Issue by isfgjspquzml** [telly/TLYShyNavBar#53]
Not sure if i'm doing something wrong but easy way to reproduce:

1. Have a tableview where the contentsize is smaller than the height.
2. Contentsize should be large enough such that when the keyboard appears the tableview can scroll up. 3. Scroll the tableview content so that the status bar shrinks
4. dismiss the keyboard, now the tableview will look how it did in step 1 but the status bar will still be shrunk and there will be a space between the shrunk status bar and the topmost cell.

Another way to reproduce: 

1. Have a tableview where the contentsize is larger than the tableview height.
2. Scroll the tableview content so that the status bar shrinks
3. Delete a tableview cell so that the contentsize is now smaller than the tableview height.
4. same scenario as in the previous situation. status bar will still be shrunk and there will be a space between the status bar and the topmost cell. 

Gonna guess the status bar height is determined by scroll events but doesn't get updated when the scrollview height changes.

**Comment by isfgjspquzml** [comment]
workaround could just be to get the initial scrollview height and whenever the content size will be smaller than that initial scrollview height (after some operation like keyboard dismissal or cell deletion) to scroll up.

**Comment by mgrider** [comment]
I am also experiencing this issue. In my case using a `UICollectionView`, and calling `reloadData` will leave a gap when the nav bar was hidden, and the data delegate has removed enough items to disable scrolling.

**Comment by Mazyod** [comment]
@isfgjspquzml @mgrider Thanks for reporting this.

TLYShyNavBar swizzles `viewDidLayoutSubviews`, which means we can easily detect the content size changes and handle the fix. If you can test it out and submit a PR, it would be greatly appreciated.

**Comment by gmxu** [comment]
Any update on this issue?
