### ISSUE TITLE
Does not works properly with custom navigation bar height

### ISSUE THREAD

**Issue by yasirmturk** [telly/TLYShyNavBar#54]
wierd behaviour seen when a custom height `UINavigationBar` is used

**Comment by Mazyod** [comment]
I think this is a duplicate of https://github.com/telly/TLYShyNavBar/issues/18. Let me know if you feel otherwise.

**Comment by yasirmturk** [comment]
that is about custom `UIStatusBar` height ..but my issue is related to `UINavigationBar` height

**Comment by Mazyod** [comment]
@yasirmturk Can you please explain more about how the `UINavigationBar` height is changing?

**Comment by yasirmturk** [comment]
@Mazyod for example my app is using a navigation bar of fixed custom height 64px instead of native 44px

**Comment by Mazyod** [comment]
@yasirmturk hmm.. I think this is a hack, right? UIKit doesn't provide height changing APIs for `UINavBar`. I will reopen it, anyway, but the solving the status bar comes first, and hopefully it will be easy to fix this as well after that.

**Comment by yasirmturk** [comment]
@Mazyod yes it does via over-riding the method
`- (CGSize)sizeThatFits:(CGSize)size`
and you can easily get the actual height via
`frame.size.height`

**Comment by Mazyod** [comment]
I am happy to say this should now be possible! The library no longer relies on the topLayoutGuide for layout, but instead uses the navigation bar frame.

Thanks for reporting this @yasirmturk !
