### ISSUE TITLE
Black background when using Swift

### ISSUE THREAD

**Issue by khoiln** [telly/TLYShyNavBar#56]
```
 self.navigationController?.navigationBar.barTintColor = UIColor(red:241/255, green:48/255, blue:29/255, alpha:1)
        self.navigationController?.navigationBar.translucent = false
```
I'm setting my bartintcolor in my view controller and I got this weird black background when I scroll down.
![img_1168](https://cloud.githubusercontent.com/assets/6994441/6615785/88cff1e6-c8d9-11e4-9720-6b838dedbf6e.PNG)

**Comment by Mazyod** [comment]
Please see #7, since your navbar is non-translucnet
