### ISSUE TITLE
Not working properly while turn on hotspot

### ISSUE THREAD

**Issue by bibuliu** [telly/TLYShyNavBar#58]
As we make a hotspot connecting, a blue toolbar, which height is 20, will appear on the top of screen. I found 2 problems with this situation.

1.TLYShyNavBar's height become larger.  
2.The connected scrollview and extensionview can't be adaptive.

**Comment by Mazyod** [comment]
@bibuliu I am pretty sure this is a duplicate #18 , and I never found the time to work on it, unfortunately :( Please refer to the other issue for updates.

Thanks for the report.
