### ISSUE TITLE
NavigationBar is drawn on top of tableview when Keyboard appears

### ISSUE THREAD

**Issue by rabzu** [telly/TLYShyNavBar#59]
Im using TLYShyNavBar in UITableViewController. I have an  InputAccessoryView with a UITextView inside. When UITextView is tapped, keyboard appears. This causes hidden navBar to be drawn on top of the keyaboard, incorrectly.

How can I manually show and hide the bar, so that when keyboard appears I can be able to hide the navbar.

thanks

**Comment by Mazyod** [comment]
Hi @rabzu 
I think you should disable the `shyNavBarManager` in `keyboardWillAppear:`. If that doesn't help, try adding `[self.navBarController expand];` inside the `setDisable` method of the shyNavBarManager

**Comment by rabzu** [comment]
Thanks @Mazyod 
I tried your advice, but it did not work. I also tried contracting the navbar via a public method that i added to the shyNavBarManager, but that did not work either plus the navbar was jerky.

However,  instead in shyNavBarManager I just uncommented:
  //  [self.navBarController expand];
in
- (void)layoutViews

**Comment by Mazyod** [comment]
Yeah, the reason it immediately scrolls up is because of cached variables not being reset, since the `expand` call has been removed. 

This is a touch edge case, will need further investigation.

**Comment by Mazyod** [comment]
The new version doesn't support `UITableViewController`, and many parts were rewritten, so I hope that resolves this issue.
