### ISSUE TITLE
Not working with my UIViewController subclass

### ISSUE THREAD

**Issue by kyco16** [telly/TLYShyNavBar#61]
```
self.shyNavBarManager.scrollView = self.tableView;
            UIView *eView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, 100)];
[eView addSubview:self.calendarMenuView];
[eView addSubview:self.calendarContentView];
[self.shyNavBarManager setExtensionView:eView];
```

This is what I am working with. I have my tableview set up exactly as your scrollview in the demo. The delegate is setup in the storyboard as well. I have tried putting this in my viewDidLoad and viewDidAppear. The `UITableView` moves but the extension and navBar do not move at all. I am importing <TLYShyNavBar/TLYShyNavBarManager.h> in the header file so I can access the shyNavBarManager. Still nothing

**Comment by Mazyod** [comment]
@kyco16 Are you setting your table view delegate anywhere?

**Comment by kyco16** [comment]
@Mazyod it is set from within the storyboard. I am also using auto layout if that makes a difference

**Comment by Mazyod** [comment]
That's really strange. I would advise adding a bunch of break points and seeing what's actually being called and what isn't. The library is very modular, and only updates the navbar in a single location, so you might want to start there.

**Comment by Mazyod** [comment]
will close for now, but please let me know if you need help.
