### ISSUE TITLE
TLYShyNavBar/TLYShyNavBarManager.h file not found when import it in *-Prefix.pch file

### ISSUE THREAD

**Issue by dg86** [telly/TLYShyNavBar#65]
I use the CocoaPods to pod this lib and then i import <TLYShyNavBar/TLYShyNavBarManager.h> in the *-Prefix.pch file => file not found.

Thanks

**Comment by Mazyod** [comment]
Sorry, if you are using cocoapods you should:
`#import <TLYShyNavBar/TLYShyNavBarManager.h>`

I will update the readme. Thanks!
