### ISSUE TITLE
Support for non-translucent navigation bars?

### ISSUE THREAD

**Issue by DimaVartanian** [telly/TLYShyNavBar#7]
I made a simple project with a UIViewController with a UITableView inside it. By default, it all works fine. Changing the translucent property of the navigation bar to NO however causes some issues. It seems the reason is this component depends on a translucent bar as it only adjusts the content inset of the scroll view (and a scrollview with a non translucent bar doesn't use this functionality since there is no hidden portion). When the navigation bar hides, it leaves a blank space in its place since the underlying view does not actually extend underneath it.

Sample project here: http://cl.ly/2D2F090o2I3d

Wondering if there is a straightforward way to solve this. 

The way I have solved it in my app for the short term is as follows:
1. manually extend the frame of the scroll view underneath the nav bar (so decreasing origin.y and increasing size.height both by the height of the navigation bar)
2. overriding topLayoutGuide to return a custom object with `length` being the height of the navigation bar so TLYShyNavBar can use that value as if the navigation bar is transparent without knowing or caring that it isn't.

This solution is working for me at the moment and behaves smoothly but has a few issues. First off, I don't see a way of easily extending this functionality into the component. The second is that overriding the layout guide seems to actually be unsupported behavior and although it is working for me, can cause some issues with autolayout, [as shown here](http://stackoverflow.com/questions/19411676/should-it-be-possible-to-implement-toplayoutguide-and-bottomlayoutguide-in-subcl).

What do you think?

**Comment by mgrider** [comment]
I also have a need for non-translucent nav bars. Odd thing is, I am using TLYShyNavBar in two views in my app, and one of them appears translucent, and the other does not. I assumed I was just missing something until reading in this thread that an opaque nav bar is not supported.

**Comment by joshbernfeld** [comment]
@iSevenDays thanks that did it for me.

**Comment by astine-daniel** [comment]
I'm using a translucent nav bar, but It's showing a black space when the nav bar is hidden. I'm using a tableview with auto layout.

**Comment by Mazyod** [comment]
@astine-daniel Thanks for reporting this. Are you sure it's translucent? There is already a demo shipping with the component that confirms it should work. If you're sure it's translucent, you may want to check #64, this issue is about non-translucent bars.
