### ISSUE TITLE
Way to make extension persistent, like Instagram?

### ISSUE THREAD

**Issue by spf2** [telly/TLYShyNavBar#70]
With instagram, there's a view which stays "pinned" right under the navigation bar.  The extension in this project seems to do something similar, except that it hides while scrolling.  Have you considered adding an option so that the extension would always be visible?

(I can also get the same effect by adding a scrollViewDidScroll handler, and translating a view based on the frame of the navigationBar.... but that's kind of tricky and seems like it might be useful to add to this functionality, no?)

**Comment by Mazyod** [comment]
Hi, are you looking for the same thing as this pr: #69 ?

**Comment by Mazyod** [comment]
I believe the new Sticky feature is what you are looking for, Kudos goes to @modastic!
