### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by schickling** [telly/TLYShyNavBar#73]
Thanks for this great package. It would be awesome if it could also be installed via [Carthage](https://github.com/Carthage/Carthage) for the Swift users among us. :+1:

**Comment by Mazyod** [comment]
Thanks, I haven't used carthage yet, so would appreciate a PR, with the Carthage badge.

**Comment by bradleyayers** [comment]
+1

**Comment by alwaysthecritic** [comment]
I found that the incantation I needed in the bridging header is slightly different to what is recommended in the readme. The readme has the following.

    #import "TLYShyNavBarManager.h"

But that doesn't work for me as XCode can't find the header. However the following does:

    #import "TLYShyNavBar/TLYShyNavBarManager.h"

I'd submit a PR, but for all I know this was working fine for most people, and the oddity is at my end.
