### ISSUE TITLE
Interactive pop gesture and scrolling at same time can cause navigation bar to remain hidden

### ISSUE THREAD

**Issue by jasonblood** [telly/TLYShyNavBar#74]
![screen shot 2015-07-06 at 15 31 49](https://cloud.githubusercontent.com/assets/2226303/8524624/49a8f24e-23f4-11e5-888d-b521a10db8f4.png)

So currently I am using this in a UITableView and if I enter the screen and scroll down a bit so the nav bar is hidden. Then if I start to dismiss the controller using the interactive swipe gesture (swiping from left of view controller) and start moving my hand up / down during it I can make the navigation bar become hidden while transitioning between the current and previous view controller.

**Comment by jasonblood** [comment]
Have this fixed currently and will put a PR when I get home.

**Comment by Mazyod** [comment]
Thanks for reporting! Do you remember which iOS version was that? I tried to reproduce on iOS 9, seems these gestures are mutually exclusive.

**Comment by ordinaryman09** [comment]
Hello,

I was able to reproduce this on iOS-9 with your demo app. I clicked on the No Extension View Test (second option) and I scroll down, and before it finished scrolling, I swiped left (and the navigation bar still hidden)

**Comment by Mazyod** [comment]
Thanks for confirming, will get to this soon.

**Comment by Mazyod** [comment]
As far as I can tell, it's resolved with v1.0.0
