### ISSUE TITLE
Extensionview is not hiding with navigation in collectionview controller

### ISSUE THREAD

**Issue by sam961** [telly/TLYShyNavBar#79]
Dear,
I create a UIViewcontroller that contains collection view, I created a view above the collectionview to be hidden when scrolling, but this is not happening.
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.view.bounds), 44.f)];
    view.backgroundColor = [UIColor redColor];
    
    //UISearchBar *search=[[UISearchBar alloc]initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.view.bounds), 44.f)];
    [self.shyNavBarManager.scrollView addSubview:self.collectionView];
    
    

    self.shyNavBarManager.scrollView = self.collectionView;

    [self.shyNavBarManager setExtensionView:view];

    [self.shyNavBarManager setStickyExtensionView:NO];
}

changing setStickyExtensionView to YES or NO doesn't have any effect

**Comment by aasatt** [comment]
Go to TLYShyNavBarManager.m.

Replace line 224 that says        

     self.navBarController.stickyExtensionView = YES;

with 

      self.navBarController.stickyExtensionView = _stickyExtensionView;

**Comment by sam961** [comment]
Thank u !! this solved it

**Comment by JaydeepPatel** [comment]
@aasatt @sam961 

Hello sir,

I am using TLYShyNavBar with CarbonKit.. when i scroll collectionview upside than TLYShyNavBar proper work . but in CarbonKitsegment not click and CarbonKittoolbar not hide when i scroll up collectionview. so please help me and guide me... 
my code is :-

- (void)viewDidLoad {

 carbonTabSwipeNavigation = [[CarbonTabSwipeNavigation alloc] initWithItems:items delegate:self];
    [carbonTabSwipeNavigation insertIntoRootViewController:self];

//    /* Library code */
    self.shyNavBarManager.scrollView = objMainHomeVC.objCollectionView;
    /* Can then be remove by setting the ExtensionView to nil */

    [self.shyNavBarManager setExtensionView:carbonTabSwipeNavigation.carbonSegmentedControl];
    
   // [self.view sendSubviewToBack:carbonTabSwipeNavigation.toolbar];
    
    [self.shyNavBarManager setStickyExtensionView:YES];
 self.navigationController.navigationBar.userInteractionEnabled = YES;

}
 i want to apply same like youtube Homeview effect on navigationbar and segmenttab.

Thank x in advance...
