### ISSUE TITLE
Extension view height not correct when scrolling.

### ISSUE THREAD

**Issue by thebirds** [telly/TLYShyNavBar#85]
I just added an extension view with height is 100px, or higher, and mark at the top with setStickyExtensionView:YES ,orange view in this image: http://prntscr.com/8mo49z
but when i scroll the collection view, the height is changed, like http://prntscr.com/8mo5fa
How can i prevent this problem?
Thanks

**Comment by Mazyod** [comment]
Thanks for reporting! Can you please try the latest release? I think it's fixed:

![](http://imgur.com/Wgr7aMQ.png)

**Comment by Mazyod** [comment]
Please note, I will update the library to 0.10.0 soon on cocoapods.
