### ISSUE TITLE
Is it possible to have a collapsing extension view, but not collapsing navigation bar

### ISSUE THREAD

**Issue by TiagoVeloso** [telly/TLYShyNavBar#87]
I would like to know if it is possible to have a collapsing extension view appended to a scrollview. But not collapsing the navigation bar.

If so what are the settings for that?

**Comment by Mazyod** [comment]
I guess this is a "sticky" navigation bar. Looking at #69 should help you find a solution, but it is not currently provided by the library.

**Comment by TiagoVeloso** [comment]
Okay, perhaps I can extend it the same way. I will PR if I do.

**Comment by TiagoVeloso** [comment]
I've opened a PR. Could you check if it is in accordance with your original work?
