### ISSUE TITLE
ContentInset issue with scroll bars 

### ISSUE THREAD

**Issue by TiagoVeloso** [telly/TLYShyNavBar#92]
I have a collection view where I am using TLYShyNavBar.
On that collection view I have added a custom scrollbar view.

Whenever I scroll up or down, and the extension view shows/hides the contentInsets are recalculated and I end up seeing my scrollbar doing somewhat of a little jump.

I am trying to set my insets manually with:

    self.automaticallyAdjustsScrollViewInsets = NO;
    self.collectionView.contentInset = UIEdgeInsetsMake(27.0f, 0.0f, 0.0f, 0.0f);

But it seems to be getting ignored

(PS, sorry for opening so many issues)

**Comment by TiagoVeloso** [comment]
I think that TLYShyNavBar ignores `self.automaticallyAdjustsScrollViewInsets` settings.

Is there any way to work around this?

**Comment by TiagoVeloso** [comment]
Further investigating this it seems that `self.extensionController.viewMaxY` jumps abruptly and not smoothly at all. Especially if contract/expand resistance is set to 0.

    Top inset: 91.000000
    Top inset: 64.000000
    Top inset: 91.000000
    Top inset: 64.000000

This causes for abrupt contentInset changes which is undesired.

**Comment by Mazyod** [comment]
Thanks for opening so many issues :) I'd really like to improve this library..

In any case, the jump you are seeing may have to do with a trick the component applies to the scrollView "smartContentInsets"

You see, the component must adjust the insets to insure that the content appears in the same position. I realize that this hack breaks scroll bar positioning.

Let me take a look at this and see if there is middle ground to support both.

**Comment by TiagoVeloso** [comment]
What I think happens is that `self.extensionController.viewMaxY` changes from one offset to another faster than it should. Especially when the Expansion/Contraction are both set to 0. Perhaps it should change gradually.

**Comment by Mazyod** [comment]
could be... Could also be related to #93, sounds close enough. Let me revert the release, and see if that solves the issue.

**Comment by Mazyod** [comment]
Thanks a lot @TiagoVeloso ! You're 100% correct, I don't know how this slipped. I changed that value to a stable calculation, and confirmed the bug was fixed. Will push v0.10.1 momentarily.
